### ISSUE TITLE
GO TO BED @Preocts

### ISSUE THREAD

**Issue by shenanigansd** [darbiadev/meta#2]
GO TO BED @Preocts

**Comment by ionite34** [comment]
Hi I'd like to get assigned on this, thanks

**Comment by Preocts** [comment]
I need to report that I'm blocked here by a cup of coffee.

**Comment by ionite34** [comment]
The issue seems to be @Preocts losing connection with the bed. I propose we establish a 2-way connection between @Preocts and the bed

![img](https://cdn.ionite.io/img/NgCcZ1.jpg)

**Comment by shenanigansd** [comment]
The sleep has been acquired
