### ISSUE TITLE
Update terminology for outdated equipment

### ISSUE THREAD

**Issue by shenanigansd** [darbiadev/meta#4]
Per [this](https://discord.com/channels/267624335836053506/464905259261755392/1054588952952180806) conversation, I have been informed that the correct terminology for equipment older than 10 years is "yee yee ass goofy lookin"

For example,
> also what sort of yee yee ass goofy lookin computer do you have that makes you hold down the power button
> \- https://discord.com/channels/267624335836053506/464905259261755392/1054587278904791070

So,the new terminology groups will look like this - 
| Age           | Term                            |
|---------------|---------------------------------|
| 1 to 5 years  | dinosaur                        |
| 5 to 10 years | goofy ahh prehistoric lookin mf |
| over 10 years | yee yee ass goofy lookin        |

We sincerely apologize for this oversight, we will get started updating all client documentation immediately!!

**Comment by Robin5605** [comment]
1-5 years - dinosaur
5-10 years - goofy ahh prehistoric lookin mf

**Comment by shenanigansd** [comment]
> 1-5 years - dinosaur 5-10 years - goofy ahh prehistoric lookin mf

Updated, thanks so much!!
